plugin:
    name: 'vdomah.botman::lang.plugin.name'
    description: 'vdomah.botman::lang.plugin.description'
    author: Art Gek
    icon: oc-icon-bolt
    homepage: 'https://github.com/vdomah/oc-botman-plugin'
